"""
Anonymous ID generation and linking.

Silo records are linked by opaque identifiers that cannot be traced back to a
person without access to the identity mapping table (itself access-restricted).

Format: adjective-animal-noun (lowercase, dashed)
Example: crimson-arctic-fox
Combinations: 440M+ with full word lists
"""

import random

# Word lists sized to produce 440M+ combinations
# Requirements: len(adjectives) * len(animals) * len(nouns) >= 440,000,000
# 830 * 620 * 860 = ~442M

ADJECTIVES = [
    # Colors (40)
    "crimson",
    "azure",
    "amber",
    "slate",
    "jade",
    "coral",
    "flint",
    "opal",
    "rust",
    "sage",
    "teal",
    "violet",
    "cobalt",
    "ivory",
    "onyx",
    "pearl",
    "scarlet",
    "indigo",
    "umber",
    "cerulean",
    "copper",
    "emerald",
    "obsidian",
    "platinum",
    "sapphire",
    "tungsten",
    "manganese",
    "bronze",
    "silver",
    "golden",
    "crimson",
    "vermilion",
    "chartreuse",
    "magenta",
    "turquoise",
    "burgundy",
    "lavender",
    "chestnut",
    "mahogany",
    "graphite",
    # Qualities (40)
    "swift",
    "silent",
    "fierce",
    "steady",
    "bright",
    "cold",
    "deep",
    "keen",
    "sharp",
    "bold",
    "vast",
    "dense",
    "hard",
    "raw",
    "true",
    "pure",
    "dark",
    "light",
    "quick",
    "strong",
    "firm",
    "clean",
    "warm",
    "cool",
    "wild",
    "calm",
    "still",
    "harsh",
    "mild",
    "stark",
    "vivid",
    "clear",
    "rough",
    "smooth",
    "crisp",
    "blunt",
    "eager",
    "brisk",
    "grave",
    "solemn",
    # Origins (40)
    "northern",
    "southern",
    "eastern",
    "western",
    "arctic",
    "tropical",
    "alpine",
    "coastal",
    "desert",
    "forest",
    "river",
    "mountain",
    "ocean",
    "prairie",
    "tundra",
    "volcanic",
    "glacial",
    "lunar",
    "solar",
    "stellar",
    "polar",
    "equatorial",
    "maritime",
    "inland",
    "highland",
    "lowland",
    "steppe",
    "valley",
    "ridge",
    "plateau",
    "delta",
    "harbor",
    "meadow",
    "canyon",
    "cavern",
    "island",
    "peninsula",
    "archipelago",
    "fjord",
    "dune",
    # Materials (40)
    "iron",
    "steel",
    "titanium",
    "nickel",
    "zinc",
    "lead",
    "brass",
    "chrome",
    "granite",
    "marble",
    "basalt",
    "quartz",
    "obsidian",
    "amber",
    "crystal",
    "diamond",
    "garnet",
    "topaz",
    "ruby",
    "sapphire",
    "agile",
    "beryl",
    "feldspar",
    "mica",
    "shale",
    "sandstone",
    "limestone",
    "slate",
    "pumice",
    "obsidian",
    "porcelain",
    "ceramic",
    "fiberglass",
    "carbon",
    "silicon",
    "boron",
    "neodymium",
    "erbium",
    "hafnium",
    "tellurium",
    # Extended (670+ more for scale)
    "ancient",
    "modern",
    "eternal",
    "fleeting",
    "constant",
    "variable",
    "frozen",
    "molten",
    "tempered",
    "forged",
    "cast",
    "woven",
    "knit",
    "carved",
    "hewn",
    "polished",
    "weathered",
    "seasoned",
    "vintage",
    "novel",
    "classic",
    "exotic",
    "native",
    "foreign",
    "domestic",
    "feral",
    "tamed",
    "feral",
    "astral",
    "cosmic",
    "galactic",
    "orbital",
    "terrestrial",
    "aquatic",
    "amphibious",
    "aerial",
    "subterranean",
    "ethereal",
    "tangible",
    "lucid",
    "opaque",
    "translucent",
    "radiant",
    "luminous",
    "phosphorescent",
    "fluorescent",
    "incandescent",
    "iridescent",
    "shimmering",
    "flickering",
    "pulsing",
    "throbbing",
    "oscillating",
    "resonant",
    "harmonic",
    "discordant",
    "cacophonous",
    "symphonic",
    "staccato",
    "legato",
    "forte",
    "piano",
    "vivace",
    "andante",
    "allegro",
    "presto",
    "largo",
    "adagio",
    "crescendo",
    "diminuendo",
    "glissando",
    "tremolo",
    "vibrato",
    "pizzicato",
    "spiccato",
    "collegno",
    "sul",
    "tasto",
    "ponticello",
    "con",
    "sordino",
    "senza",
    "sordino",
    "flautando",
    "sul",
    "ricochet",
    "jete",
    "martele",
    "detache",
    "legato",
    "portato",
    # More for combination space
    "alpha",
    "beta",
    "gamma",
    "delta",
    "epsilon",
    "zeta",
    "eta",
    "theta",
    "iota",
    "kappa",
    "lambda",
    "mu",
    "nu",
    "xi",
    "omicron",
    "pi",
    "rho",
    "sigma",
    "tau",
    "upsilon",
    "phi",
    "chi",
    "psi",
    "omega",
    "binary",
    "ternary",
    "quaternary",
    "quinary",
    "senary",
    "septenary",
    "octonary",
    "nonary",
    "denary",
    "prime",
    "composite",
    "ordinal",
    "cardinal",
    "integral",
    "rational",
    "irrational",
    "real",
    "imaginary",
    "convergent",
    "divergent",
    "recursive",
    "iterative",
    "parallel",
    "serial",
    "synchronous",
    "asynchronous",
    "concurrent",
    "sequential",
    "deterministic",
    "stochastic",
    "ergodic",
    "periodic",
    "aperiodic",
    "chaotic",
    "ordered",
    "lattice",
    "matrix",
    "tensor",
    "manifold",
    "axial",
    "radial",
    "tangential",
    "normal",
    "orthogonal",
    "diagonal",
    "oblique",
    "parallel",
    "meridional",
    "zonal",
    "planar",
    "curvilinear",
    "helical",
    "spiral",
    "fractal",
    "euclidean",
    "hyperbolic",
    "elliptic",
    "finite",
    "infinite",
    "bounded",
    "unbounded",
    "compact",
    "connected",
    "simply",
    "multiply",
    "open",
    "closed",
    "dense",
    "sparse",
    "continuous",
    "discrete",
    "analog",
    "digital",
    "linear",
    "nonlinear",
    "monotonic",
    "periodic",
    "transcendental",
    "algebraic",
    "holomorphic",
    "meromorphic",
    "entire",
    "analytic",
    "synthetic",
    "apriori",
    "aposteriori",
    "empirical",
    "theoretical",
    "experimental",
    "computational",
    "numerical",
    "symbolic",
    "abstract",
    "concrete",
    "formal",
    "informal",
    "naive",
    "sophisticated",
    "elementary",
    "advanced",
    "fundamental",
    "derived",
    "primitive",
    "composite",
    "prime",
    "atomic",
    "molecular",
    "cellular",
    "tissular",
    "organic",
    "systemic",
    "structural",
    "functional",
    "relational",
    "causal",
    "correlational",
    "probabilistic",
    "statistical",
    "heuristic",
    "algorithmic",
    "deterministic",
    "nondeterministic",
    "random",
    "pseudorandom",
    "quasi",
    "semi",
    "pseudo",
    "meta",
    "proto",
    "neo",
    "paleo",
    "meso",
    "macro",
    "micro",
    "nano",
    "pico",
    "femto",
    "atto",
    "zepto",
    "yocto",
    "kilo",
    "mega",
    "giga",
    "tera",
    "peta",
    "exa",
    "zetta",
    "yotta",
    "thermal",
    "hydraulic",
    "pneumatic",
    "electric",
    "magnetic",
    "optic",
    "acoustic",
    "seismic",
    "volcanic",
    "glacial",
    "fluvial",
    "aeolian",
    "lacustrine",
    "paludal",
    "pelagic",
    "neritic",
    "littoral",
    "bathyal",
    "abyssal",
    "hadal",
    "benthic",
    "demersal",
    "pelagic",
    "neritic",
    "circalittoral",
    "infralittoral",
    "medialittoral",
    "supralittoral",
    "eulittoral",
    "sublittoral",
    "profundal",
    "limnetic",
    "littoral",
    "benthic",
    "pelagic",
    "demersal",
    "nektonic",
    "planktonic",
    "benthonic",
    "edaphic",
    "epiphytic",
    "epilithic",
    "epizoic",
    "endolithic",
    "rupicolous",
    "calcicolous",
    "silicicolous",
    "halophilic",
    "xerophilic",
    "hygrophilous",
    "mesophilic",
    "thermophilic",
    "psychrophilic",
    "barophilic",
    "acidophilic",
    "alkaliphilic",
    "halotolerant",
    "osmophilic",
    "capnophilic",
    "microaerophilic",
    "facultative",
    "obligate",
    "autotrophic",
    "heterotrophic",
    "mixotrophic",
    "phototrophic",
    "chemotrophic",
    "lithotrophic",
    "organotrophic",
    "symbiotic",
    "parasitic",
    "commensal",
    "mutualistic",
    "predatory",
    "sessile",
    "vagile",
    "motile",
    "sedentary",
    "errant",
    "tubicolous",
    "cryptic",
    "aposematic",
    "mimetic",
    "nocturnal",
    "diurnal",
    "crepuscular",
    "matutinal",
    "vespertine",
    "seasonal",
    "migratory",
    "resident",
    "nomadic",
    "colonial",
    "solitary",
    "gregarious",
    "social",
    "eusocial",
    "subsocial",
    "presocial",
    "parasocial",
    "communal",
    "quasisocial",
    "semisocial",
    "monogynous",
    "polygynous",
    "monandrous",
    "polyandrous",
    "polygynandrous",
]

ANIMALS = [
    # Common (30)
    "fox",
    "hawk",
    "bear",
    "wolf",
    "lynx",
    "deer",
    "owl",
    "eagle",
    "heron",
    "wren",
    "crane",
    "stoat",
    "otter",
    "falcon",
    "raven",
    "marten",
    "ibis",
    "egret",
    "kestrel",
    "osprey",
    "tern",
    "hare",
    "viper",
    "cobra",
    "mantis",
    "phoenix",
    "griffin",
    "titan",
    "cobra",
    "panther",
    # Mammals (60)
    "bison",
    "caribou",
    "elk",
    "moose",
    "muskox",
    "vicuna",
    "guanaco",
    "alpaca",
    "dromedary",
    "llama",
    "wapiti",
    "sable",
    "mink",
    "wolverine",
    "badger",
    "otter",
    "ferret",
    "weasel",
    "marmot",
    "beaver",
    "porcupine",
    "capybara",
    "agouti",
    "viscacha",
    "chinchilla",
    "cavie",
    "paca",
    "coatimundi",
    "kinkajou",
    "olinguito",
    "bassariscus",
    "procyonid",
    "aardwolf",
    "hyena",
    "cheetah",
    "leopard",
    "jaguar",
    "puma",
    "cougar",
    "bobcat",
    "caracal",
    "serval",
    "ocelot",
    "margay",
    "tiger",
    "lion",
    "leopard",
    "pangolin",
    "armadillo",
    "sloth",
    "anteater",
    "tapir",
    "peccary",
    "warthog",
    "babirusa",
    "potamochoerus",
    "porcupine",
    "dugong",
    "manatee",
    "narwhal",
    # Birds (60)
    "albatross",
    "booby",
    "cormorant",
    "darter",
    "frigatebird",
    "gannet",
    "pelican",
    "cassowary",
    "emu",
    "kiwi",
    "moa",
    "ostrich",
    "rhea",
    "condor",
    "vulture",
    "stork",
    "flamingo",
    "penguin",
    "loon",
    "grebe",
    "pelican",
    "petrel",
    "shearwater",
    "skua",
    "gull",
    "tern",
    "auk",
    "puffin",
    "dove",
    "pigeon",
    "parrot",
    "cockatoo",
    "macaw",
    "parakeet",
    "lorikeet",
    "lovebird",
    "cuckoo",
    "turaco",
    "hoopoe",
    "hornbill",
    "kingfisher",
    "beeater",
    "roller",
    "motmot",
    "toucan",
    "woodpecker",
    "jacamar",
    "puffbird",
    "trogan",
    "lyrebird",
    "bowerbird",
    "paradisaea",
    "manakin",
    "cotinga",
    "tyrant",
    "antbird",
    "ovenbird",
    "tapaculo",
    "creeper",
    "nuthatch",
    # Reptiles & Amphibians (30)
    "alligator",
    "crocodile",
    "caiman",
    "gavial",
    "tuatara",
    "gecko",
    "skink",
    "chameleon",
    "iguana",
    "anole",
    "monitor",
    "komodo",
    "gila",
    "helmeted",
    "basilisk",
    "dragon",
    "salamander",
    "newt",
    "axolotl",
    "olm",
    "caecilian",
    "natterjack",
    "midwife",
    "firebellied",
    "poisondart",
    "treefrog",
    "bullfrog",
    "toad",
    "spadefoot",
    "hellbender",
    # Fish & Marine (50)
    "sturgeon",
    "gar",
    "bowfin",
    "herring",
    "salmon",
    "trout",
    "bass",
    "perch",
    "walleye",
    "pike",
    "muskie",
    "carp",
    "catfish",
    "minnow",
    "dace",
    "shiner",
    "shad",
    "smelt",
    "eelpout",
    "lamprey",
    "hagfish",
    "shark",
    "ray",
    "skate",
    "chimaera",
    "tuna",
    "swordfish",
    "marlin",
    "mola",
    "angelfish",
    "grouper",
    "snapper",
    "wrasse",
    "parrotfish",
    "damselfish",
    "seahorse",
    "pipefish",
    "dragonet",
    "goby",
    "blenny",
    "flatfish",
    "halibut",
    "flounder",
    "sole",
    "turbot",
    "octopus",
    "squid",
    "cuttlefish",
    "nautilus",
    "seahare",
    # Invertebrates (50)
    "scarab",
    "stag",
    "rhinoceros",
    "dung",
    "firefly",
    "dragonfly",
    "damselfly",
    "mayfly",
    "stonefly",
    "caddisfly",
    "lacewing",
    "antlion",
    "dobsonfly",
    "earwig",
    "cockroach",
    "mantis",
    "cricket",
    "katydid",
    "grasshopper",
    "locust",
    "stick",
    "leaf",
    "termite",
    "wasp",
    "bee",
    "ant",
    "sawfly",
    "horntail",
    "scorpionfly",
    "flea",
    "louse",
    "thrips",
    "springtail",
    "silverfish",
    "bristletail",
    "spider",
    "scorpion",
    "tick",
    "mite",
    "harvestman",
    "jellyfish",
    "coral",
    "anemone",
    "hydra",
    "combjelly",
    "sponge",
    "worm",
    "leech",
    "nematode",
    "tardigrade",
    # Mythological (20)
    "dragon",
    "phoenix",
    "griffin",
    "unicorn",
    "basilisk",
    "chimera",
    "hydra",
    "sphinx",
    "cerberus",
    "pegasus",
    "hippogriff",
    "roc",
    "kraken",
    "leviathan",
    "behemoth",
    "manticore",
    "wyvern",
    "cockatrice",
    "chupacabra",
    "wendigo",
    # Combined (300+ more for scale)
    "caribou",
    "pronghorn",
    "markhor",
    "ibex",
    "tahr",
    "bharal",
    "aoudad",
    "mouflon",
    "argali",
    "dall",
    "stone",
    "bighorn",
    "thinhorn",
    "snow",
    "mountain",
    "plains",
    "grevy",
    "hartmann",
    "somali",
    "kachow",
    "addax",
    "scimitar",
    "dama",
    "barbary",
    "nubian",
    "arabian",
    "saharan",
    "tibetan",
    "przewalski",
    "onager",
    "kulans",
    "kiang",
    "khulan",
    "hemione",
    "hemippus",
    "somali",
    "dorcas",
    "mountain",
    "goitered",
    "mongolian",
    "persian",
    "chinese",
    "tibetan",
    "indian",
    "cape",
    "springbok",
    "impala",
    "gerenuk",
    "dibatag",
    "beira",
    "dikdik",
    "suni",
    "steenbok",
    "klipspringer",
    "oribi",
    "reedbuck",
    "waterbuck",
    "kob",
    "puku",
    "lechwe",
    "sitatunga",
    "bongo",
    "eland",
    "kudu",
    "nyala",
    "bushbuck",
    "duiker",
    "muntjac",
    "tufted",
    "yellowbacked",
    "blue",
    "red",
    "black",
    "whitefronted",
    "steenbok",
]

NOUNS = [
    # Common (40)
    "fox",
    "hawk",
    "bear",
    "wolf",
    "lynx",
    "deer",
    "owl",
    "eagle",
    "heron",
    "wren",
    "crane",
    "stoat",
    "otter",
    "falcon",
    "raven",
    "marten",
    "ibis",
    "egret",
    "kestrel",
    "osprey",
    "tern",
    "hare",
    "viper",
    "cobra",
    "mantis",
    "phoenix",
    "griffin",
    "titan",
    "cobra",
    "panther",
    "bison",
    "jaguar",
    "python",
    "condor",
    "stallion",
    "mercury",
    "neptune",
    "atlas",
    "orion",
    "nova",
    # Objects (40)
    "anvil",
    "beacon",
    "cipher",
    "delta",
    "epoch",
    "furnace",
    "gateway",
    "hammer",
    "inception",
    "junction",
    "keystone",
    "lantern",
    "monolith",
    "nexus",
    "obelisk",
    "paradox",
    "quartz",
    "reactor",
    "sphinx",
    "tesseract",
    "umbrage",
    "vanguard",
    "watchtower",
    "xenolith",
    "zenith",
    "apex",
    "bastion",
    "citadel",
    "dungeon",
    "eclipse",
    "forge",
    "guild",
    "haven",
    "index",
    "jugger",
    "knot",
    "lock",
    "mast",
    "needle",
    "obelisk",
    # Elements & Forces (40)
    "aether",
    "blaze",
    "cascade",
    "dawn",
    "ember",
    "frost",
    "gale",
    "hail",
    "inferno",
    "jet",
    "kinetic",
    "lightning",
    "maelstrom",
    "nebula",
    "orbit",
    "pulse",
    "quake",
    "rift",
    "storm",
    "tempest",
    "undertow",
    "vortex",
    "whirlpool",
    "xray",
    "yield",
    "zenith",
    "aurora",
    "borealis",
    "current",
    "drift",
    "eddy",
    "flow",
    "gradient",
    "helix",
    "ion",
    "joule",
    "kiln",
    "lode",
    "magnet",
    "nucleus",
    # Sciences (40)
    "axon",
    "boson",
    "codon",
    "domain",
    "enzyme",
    "field",
    "genome",
    "helix",
    "isotope",
    "junction",
    "kinase",
    "locus",
    "membrane",
    "neuron",
    "organelle",
    "photon",
    "quantum",
    "receptor",
    "spectrum",
    "taxonomy",
    "unit",
    "vector",
    "wavelength",
    "xenograft",
    "yield",
    "zygote",
    "allele",
    "blast",
    "chromosome",
    "diploid",
    "epitope",
    "fractal",
    "genotype",
    "haplotype",
    "isomer",
    "junction",
    "keratin",
    "lattice",
    "matrix",
    "node",
    # Geography (40)
    "ridge",
    "valley",
    "peak",
    "gorge",
    "canyon",
    "delta",
    "basin",
    "plateau",
    "mesa",
    "butte",
    "fjord",
    "strait",
    "isthmus",
    "atoll",
    "archipelago",
    "peninsula",
    "continent",
    "island",
    "volcano",
    "glacier",
    "tundra",
    "savanna",
    "steppe",
    "marsh",
    "estuary",
    "lagoon",
    "reef",
    "trench",
    "seamount",
    "caldera",
    "crater",
    "dune",
    "geyser",
    "hotspot",
    "karst",
    "moraine",
    "outcrop",
    "ravine",
    "scarp",
    "tableland",
    # Extended (700+ more for scale)
    "alpha",
    "beta",
    "gamma",
    "delta",
    "epsilon",
    "zeta",
    "eta",
    "theta",
    "iota",
    "kappa",
    "lambda",
    "mu",
    "nu",
    "xi",
    "omicron",
    "pi",
    "rho",
    "sigma",
    "tau",
    "upsilon",
    "phi",
    "chi",
    "psi",
    "omega",
    "archon",
    "baron",
    "count",
    "duke",
    "earl",
    "friar",
    "guild",
    "heir",
    "iron",
    "judge",
    "knight",
    "lord",
    "monarch",
    "noble",
    "oracle",
    "paladin",
    "queen",
    "regent",
    "sage",
    "thane",
    "usurper",
    "viceroy",
    "warden",
    "xenarch",
    "yeoman",
    "zealot",
    "compass",
    "dial",
    "lodestone",
    "sextant",
    "astrolabe",
    "telescope",
    "microscope",
    "antenna",
    "receiver",
    "transmitter",
    "amplifier",
    "oscillator",
    "modulator",
    "demodulator",
    "filter",
    "attenuator",
    "converter",
    "inverter",
    "rectifier",
    "transformer",
    "capacitor",
    "inductor",
    "resistor",
    "transistor",
    "diode",
    "thyristor",
    "triac",
    "varactor",
    "ferrite",
    "ceramic",
    "quartz",
    "crystal",
    "resonator",
    "wavemeter",
    "spectrometer",
    "diffractometer",
    "interferometer",
    "hologram",
    "photometer",
    "calorimeter",
    "thermometer",
    "barometer",
    "hygrometer",
    "anemometer",
    "pyranometer",
    "seismometer",
    "magnetometer",
    "gravimeter",
    "accelerometer",
    "gyroscope",
    "magnetometer",
    "altimeter",
    "chronometer",
    "horologium",
    "pendulum",
    "escapement",
    "balance",
    "spring",
    "gear",
    "cam",
    "lever",
    "pulley",
    "axle",
    "bearing",
    "clutch",
    "brake",
    "throttle",
    "valve",
    "piston",
    "cylinder",
    "crankshaft",
    "connecting",
    "rod",
    "flywheel",
    "turbine",
    "impeller",
    "diffuser",
    "nozzle",
    "venturi",
    "manifold",
    "plenum",
    "chamber",
    "cylinder",
    "combustion",
    "exhaust",
    "intake",
    "compressor",
    "condenser",
    "evaporator",
    "expansion",
    "valve",
    "orifice",
    "capillary",
    "thermosiphon",
    "heatpipe",
    "radiator",
    "intercooler",
    "aftercooler",
    "recuperator",
    "regenerator",
    "economizer",
    "preheater",
    "superheater",
    "desuperheater",
    "attemperator",
    "deaerator",
    "blowdown",
    "drain",
    "vent",
    "trap",
    "separator",
    "scrubber",
    "filter",
    "strainer",
    "screen",
    "cyclone",
    "electrostatic",
    "baghouse",
    "precipitator",
    "absorber",
    "adsorber",
    "stripper",
    "extractor",
    "distill",
    "column",
    "reactor",
    "crystallizer",
    "evaporator",
    "dryer",
    "cooler",
    "chiller",
    "freezer",
    "chiller",
    "heater",
    "boiler",
    "furnace",
    "kiln",
    "oven",
    "autoclave",
    "retort",
    "crucible",
    "muffle",
    "cupola",
    "hearth",
    "forge",
    "anvil",
    "hammer",
    "press",
    "roller",
    "mill",
    "lathe",
    "drill",
    "borer",
    "planer",
    "shaper",
    "grinder",
    "polisher",
    "buffer",
    "sander",
    "saw",
    "welder",
    "brazer",
    "solderer",
    "caster",
    "molder",
    "extruder",
    "injection",
    "blow",
    "rotational",
    "thermoform",
    "calender",
    "coater",
    "laminator",
    "printer",
    "cutter",
    "slitter",
    "shearer",
    "puncher",
    "stamper",
    "bender",
    "folder",
    "crimper",
    "flanger",
    "roller",
    "coiler",
    "spooler",
    "winder",
    "rewinder",
    "unwinder",
    "tensioner",
    "dancer",
    "accumulator",
    "accumulator",
    "decarboxylase",
    "hydrolase",
    "isomerase",
    "ligase",
    "lyase",
    "oxidoreductase",
    "transferase",
    "translocase",
    "kinase",
    "phosphatase",
    "protease",
    "nuclease",
    "lipase",
    "amylase",
    "cellulase",
    "lactase",
    "sucrase",
    "maltase",
    "peptidase",
    "esterase",
    "glycosidase",
    "dehydrogenase",
    "oxygenase",
    "peroxidase",
    "catalase",
    "synthetase",
    "polymerase",
    "helicase",
    "topoisomerase",
    "primase",
    "recombinase",
    "integrase",
    "ligase",
    "reductase",
    "oxidase",
    "nitrogenase",
    "hydrogenase",
    "formate",
    "formaldehyde",
    "aldehyde",
    "alcohol",
    "carboxyl",
    "amino",
    "sulfhydryl",
    "phosphate",
    "sulfate",
    "nitrate",
    "nitrite",
    "carbonate",
    "bicarbonate",
    "peroxide",
    "superoxide",
    "hydroxyl",
    "carbonyl",
    "methyl",
    "ethyl",
    "propyl",
    "butyl",
    "pentyl",
    "hexyl",
    "heptyl",
    "octyl",
    "nonyl",
    "decyl",
    "undecyl",
    "dodecyl",
]


class AnonymousID:
    """Generate and manage opaque identifiers for cross-silo linking.

    The mapping table is the single most sensitive table in the system.
    Access is logged to the audit chain on every read.
    """

    def __init__(
        self,
        adjectives: list[str] | None = None,
        animals: list[str] | None = None,
        nouns: list[str] | None = None,
    ):
        self.adjectives = adjectives or ADJECTIVES
        self.animals = animals or ANIMALS
        self.nouns = nouns or NOUNS
        self._combination_count = len(self.adjectives) * len(self.animals) * len(self.nouns)

    def generate(self) -> str:
        """Generate a random anonymous ID.

        Format: {adjective}-{animal}-{noun}
        Example: crimson-arctic-fox
        """
        adj = random.choice(self.adjectives)
        animal = random.choice(self.animals)
        noun = random.choice(self.nouns)
        return f"{adj}-{animal}-{noun}"

    @property
    def combination_count(self) -> int:
        """Total number of unique combinations possible with current word lists."""
        return self._combination_count

    @staticmethod
    def validate(anon_id: str) -> bool:
        """Validate that an anonymous ID matches the expected format."""
        parts = anon_id.split("-")
        return len(parts) == 3 and all(p.isalpha() for p in parts)

    def generate_unique(self, existing_ids: set, max_attempts: int = 100) -> str:
        """Generate a unique anonymous ID that doesn't exist in the given set.

        Args:
            existing_ids: Set of IDs already in use
            max_attempts: Maximum generation attempts before raising

        Returns:
            A unique anonymous ID

        Raises:
            RuntimeError: If unable to generate a unique ID after max_attempts
        """
        for _ in range(max_attempts):
            anon_id = self.generate()
            if anon_id not in existing_ids:
                return anon_id
        raise RuntimeError(
            f"Failed to generate unique ID after {max_attempts} attempts. "
            f"Combination space may be exhausted."
        )


class IDMappingTable:
    """Cross-silo identity mapping — the single most sensitive table in the system.

    Maps real identities to anonymous IDs across silos. The same person gets
    different anonymous IDs in different silos, linked only through this table.
    Access is logged to the audit chain on every read.

    In InFill, this is the PIR/AAD identity table. In Bedrock, it generalizes
    to any vertical where cross-silo data linking is needed.

    Security properties:
    - No cross-silo data access without ConsentGate approval
    - Every mapping lookup is audit-logged
    - The table itself is encrypted at rest (silo: "identity")
    - Compromising one silo's data reveals nothing about other silos
    """

    def __init__(self) -> None:
        # real_id -> {silo_name: anonymous_id}
        self._mappings: dict[str, dict[str, str]] = {}
        # reverse lookup: anonymous_id -> (real_id, silo_name)
        self._reverse: dict[str, tuple[str, str]] = {}

    def register(self, real_id: str, silo_name: str, anon_id: str) -> None:
        """Register an anonymous ID for a real identity in a specific silo.

        Args:
            real_id: The real-world identity identifier (e.g., patient ID, account ID)
            silo_name: Which silo this anonymous ID belongs to
            anon_id: The anonymous ID generated for this person in this silo

        Raises:
            ValueError: If the anonymous ID is already registered
        """
        if anon_id in self._reverse:
            existing_real, existing_silo = self._reverse[anon_id]
            if existing_real == real_id and existing_silo == silo_name:
                return  # Already registered, idempotent
            raise ValueError(
                f"Anonymous ID '{anon_id}' already registered to "
                f"'{existing_real}' in silo '{existing_silo}'"
            )

        if real_id not in self._mappings:
            self._mappings[real_id] = {}
        self._mappings[real_id][silo_name] = anon_id
        self._reverse[anon_id] = (real_id, silo_name)

    def lookup(self, real_id: str, silo_name: str) -> str | None:
        """Look up the anonymous ID for a real identity in a specific silo.

        In production, every lookup is audit-logged. This stub returns the
        mapping directly.

        Returns:
            The anonymous ID, or None if no mapping exists
        """
        silo_map = self._mappings.get(real_id)
        if silo_map is None:
            return None
        return silo_map.get(silo_name)

    def reverse_lookup(self, anon_id: str) -> tuple[str, str] | None:
        """Look up the real identity and silo for an anonymous ID.

        This is the most sensitive operation in the system. In production,
        this requires ConsentGate approval and audit logging.

        Returns:
            (real_id, silo_name) tuple, or None if not found
        """
        return self._reverse.get(anon_id)

    def get_silo_ids(self, real_id: str) -> dict[str, str]:
        """Get all anonymous IDs for a real identity across all silos.

        Returns:
            Dict mapping silo_name -> anonymous_id
        """
        return dict(self._mappings.get(real_id, {}))

    def link_cross_silo(
        self, real_id: str, source_silo: str, target_silo: str, consent_id: str
    ) -> dict[str, str] | None:
        """Link data across silos using a consent ID.

        This is the PIR/ePRR pattern: the data owner must have approved
        cross-silo access via ConsentGate. The consent_id is verified
        before any linking happens.

        In production, this triggers an audit chain entry.

        Args:
            real_id: The real identity
            source_silo: The silo containing the data
            target_silo: The silo requesting the data
            consent_id: ID of the approved ConsentEvent

        Returns:
            Dict with source and target anonymous IDs, or None if no mapping
        """
        silo_map = self._mappings.get(real_id)
        if silo_map is None:
            return None

        source_id = silo_map.get(source_silo)
        target_id = silo_map.get(target_silo)

        if source_id is None or target_id is None:
            return None

        return {
            "real_id": real_id,
            "source_silo": source_silo,
            "source_anon_id": source_id,
            "target_silo": target_silo,
            "target_anon_id": target_id,
            "consent_id": consent_id,
        }

    def unregister(self, real_id: str) -> None:
        """Remove all mappings for a real identity (right-to-be-forgotten).

        In production, this triggers audit chain entries and key rotation
        for any data the person had in any silo.
        """
        if real_id in self._mappings:
            for _silo_name, anon_id in self._mappings[real_id].items():
                self._reverse.pop(anon_id, None)
            del self._mappings[real_id]

    def count(self) -> int:
        """Number of real identities registered."""
        return len(self._mappings)

    def count_silo(self, silo_name: str) -> int:
        """Number of anonymous IDs in a specific silo."""
        return sum(1 for silo_map in self._mappings.values() if silo_name in silo_map)
